//页面跳转
angular.module("myapp")
	.config(function($stateProvider,$urlRouterProvider,$ocLazyLoadProvider){
	//console.log(1);
	$urlRouterProvider.otherwise("index")

	$stateProvider
		.state("index",{
			url:"/index",
			templateUrl:"view/index.html",
			controller:"indexS"
			/*resolve:{
	    		loadPlugin:function($ocLazyLoad){
	    			return $ocLazyLoad.load([
		    			{
		    				files:["./css/style.css","./js/Swiper/dist/css/swiper.min.css","./js/Swiper/dist/js/swiper.min.js"]
		    			}
    				])
	    		}
	    	}*/
		})
		.state("index_n1",{
			url:"/index_n1",
			templateUrl:"view/index_n1.html",
			controller:"indexS"
		})
		.state("index_n2",{
			url:"/index_n2",
			templateUrl:"view/index_n2.html",
			controller:"indexS"

		})
		.state("hot",{
			url:"/hot",
			templateUrl:"view/hot.html",
			controller:"indexS"
		})
		.state("hot_n1",{
			url:"/hot_n1",
			templateUrl:"view/hot_n1.html",
			controller:"indexS"
		})
		.state("hot_write",{
			url:"/hot_write",
			templateUrl:"view/hot_write.html",
			controller:"indexS"
		})
		.state("bei",{
			url:"/bei",
			templateUrl:"view/bei.html",
			controller:"indexS"
		})
		.state("bei_map",{
			url:"/bei_map",
			templateUrl:"view/bei_map.html",
			controller:"indexS"
		})
		.state("play",{
			url:"/play",
			templateUrl:"view/play.html",
			controller:"indexS"
		})
		.state("add",{
			url:"/add",
			templateUrl:"view/add.html",
			controller:"indexS"
		})
		.state("play_n1",{
			url:"/play_n1",
			templateUrl:"view/play_n1.html",
			controller:"indexS"
		})
		.state("search",{
			url:"/search",
			templateUrl:"view/search.html",
			controller:"indexS"
		})
		.state("myself",{
			url:"/myself",
			templateUrl:"view/myself.html",
			controller:"indexS"
		})
		.state("login",{
			url:"/login",
			templateUrl:"view/login.html",
			controller:"indexS"
		})
	})